src/app/hooks/use-data-by-name/use-data-by-name.test.ts, src/app/services/data/courses-path.data.ts, src/app/services/data/courses.data.ts, src/features/home/courses/courses.tsx
=> fix: courses info

src/app/services/data/courses.data.ts
Is there anything else should be updated?
=> feat: update AWS Fundamentals 2024q2 run course data

src/features/home/about/about.tsx
=> fix: remove information about ios, android

src/app/services/data/courses-path.data.ts
- Related Issue #47 
- Closes #47
=> fix: courses path links

src/features/about/about.data.ts, src/features/about/about.tsx, src/features/about/components/info-grid/info-grid.scss, src/features/about/components/info-grid/info-grid.tsx, src/features/courses/general/general.scss, src/features/courses/general/general.test.tsx, src/features/courses/general/general.tsx, src/features/home/courses/courses.test.tsx, src/features/home/courses/courses.tsx
- Related Issue #40
- Closes #40
=> Fix: add/update discord and other links

src/app/components/paragraph/paragraph.tsx, src/features/home/alumni/alumni.tsx
Added semantic tags to Alumni component. Included tags are: article, section, figure, p.
It would be better to use H2 & H3 tags in the Title & Subtitle components respectively, but we decided to revise and change these components soon, so I think it will be include to another task.
- Closes #60
=> Add semantiс tags into Alumni component

src/features/base-layout/components/navbar/dropdown.tsx, src/features/base-layout/components/navbar/nav-item.tsx, src/features/base-layout/components/navbar/navbar.test.tsx
Change drop down menu to open on hover INSTEAD of click
- Related Issue #65 
- Closes #65 
https://github.com/rolling-scopes/site/assets/46446962/dab4c1f9-83ca-4711-99f6-6e522febfecb
=> Feature: change drop down menu to open on hover

.github/CODEOWNERS, package-lock.json, package.json
All dependencies updated and new CODEOWNER added
- Related Issue #79 
- Closes #79
- Related Issue #99  
- Closes #99
- Related Issue #87  
- Closes #87
=> Refactor/update dependencies & CODEOWNERS

src/features/training-program/training-program.data.tsx
Update React course with the new description
- Related Issue #106 
- Closes #106
=> Refactor/Update React course description

package.json
Fixed quotes in `*.scss` files mask for Windows OS
- Related Issue #72 
- Closes #123 
=> Fix Stylelint linting for WindowsOS

src/features/trainers/angular.data.ts
Remove mentor Dzmitry (@spanb4) from Angular course.
- Related Issue #120
- Closes #120
=> Fix: remove mentor from Angular course

readme/__rs_school_website_documentation.md, readme/git-pullrequest-workflow.md, readme/onboarding.md, readme/styleguide-design.md, readme/tests.md, readme/volunteering.md
=> feat: Purpose of the RS.School Website

.github/workflows/main.yml
stylelint check added to ci/cd pipeline
- Related Issue #161 
- Closes #161
=> feature/add stylelint check to ci/cd pipeline

src/features/courses/about/about.scss, src/features/courses/mentors/mentors.scss, src/features/home/about/about.scss, src/features/home/community/community.scss, src/features/home/contribute/contribute.scss, src/features/home/events/events.scss, src/features/home/school/school.scss, src/features/home/speakers/speakers.scss, src/features/home/support/support.scss, src/features/required/required.scss, src/features/study-path/study-path.scss
Fixed limited block width for some text blocks, and set in to max block width to spread text for a whole screen, exactly in courses page, main page 
- Related Issue #131 
- Closes #131
Please, check out if verything is ok at safari browser.
=> Fix: fix text width for some blocks

readme/git-pullrequest-workflow.md
- Related Issue #159 
- Closes #159
=> 159:doc - Git Pull Request Workflow Guidelines done

readme/semantic-webaccessibility.md
- [x ] 📝 Documentation Update
#42
=> feat: semantic html doc

src/app/components/breadcrumbs/constants.ts, src/pages/aws-developer.tsx
- Related Issue #173 
- Closes #173
=> Fix: add breadcrubms for aws course

src/features/courses/mentors/mentors.scss
- Related Issue #175 
- Closes #175
=> fix: fix blocks width in mentors section

src/features/course-main/course-main.module.scss
- Related Issue #172 
- Closes #172
=> fix: fix courses first section min height

vite.config.ts
Changed Vite Config - `localsConvention` param for modules changed to `camelCase` instead `camelCaseOnly`
- Related Issue #145 
- Closes #206
=> Change Vite Config

README.md
1. **Project Introduction:**
2. **Technology Overview:**
3. **Launch Instructions:**
4. **Community Engagement:**
5. **Formatting and Readability:**
- Related Issue #174
- Closes #174
=> Documentation: replace the template readme file with additional information

README.md
=> Readme.md refactoring

.github/workflows/tag-pr.yml
Automatically add label 'preview' when we're create PR
- Related Issue #244 
- Closes #244
=> 244-feat: Automatically add label 'preview' when creating PR

.github/ISSUE_TEMPLATE/bug-report.md
- [X ] 📝 Documentation Update
Changed the description of the bug reports' sample to provide more information for the developers in future.
- Related Issue #290
- Closes #290 
=> 290-doc: Edit sample of the bug report

src/app/components/mobile-view/mobile-view.scss, src/features/base-layout/components/header/burger/burger.module.scss
- fixed for android: burger overlay, bottom menu indent
- check performs on the deployed application
- Related Issue #293
- Closes #293
=> 293-fix: Mobile menu layout bugs

eslint.config.js
Add `restrictDefaultExports` `ESLint` rule for all types of `default` exports
- Related Issue #365 
- Closes #365
=> 365-feat: Add restrict default exports ESLint rule

.github/CODEOWNERS
Updated code owners for improved repository management:
- Added ownership for `@Quiddlee`, `@ansivgit`, and `@natanchik` to the `src/` directory.
- Updated `.github/` directory ownership by removing `@apalchys` and adding `@Quiddlee`.
- Related Issue #398 
- Closes #398
=> 398-chore: modify codeowners

.github/workflows/visual-testing.yml
=> fix: visual testing workflow

.github/workflows/visual-testing.yml
=> Workflow another fix 2

.github/workflows/visual-testing.yml
=> Workflow another fix 3

package-lock.json, package.json, src/app/layout.tsx
- Related Issue #529 
- Closes #529
=> 529-refactor: Remove loader

dev-data/courses.data.ts
- Related Issue #691 
- Closes #691 
=> 691-feat: Update node registration link

src/widgets/speakers/ui/speakers.module.scss
- Related Issue #696 
- Closes #696 
=> 696-fix: Speakers wanted layout issue

dev-data/index.ts, dev-data/mentorship-data.types.ts, next-env.d.ts, src/app/mentorship/[course]/page.tsx, src/app/mentorship/page.tsx, src/entities/course/ui/course-card/course-card.tsx, src/views/mentorship/constants.ts, src/views/mentorship/helpers/transformCoursesToMentorship.ts, src/views/mentorship/mentorship.tsx, src/views/mentorship/ui/mentorship-courses/mentorship-courses.module.scss, src/views/mentorship/ui/mentorship-courses/mentorship-courses.test.tsx, src/views/mentorship/ui/mentorship-courses/mentorship-courses.tsx
- Related Issue #716 
- Closes #716
=> 716-feat: Mentorship courses

.github/workflows/main.yml, .github/workflows/preview-create.yml, .github/workflows/production.yml, .github/workflows/visual-testing-on-comment.yml, .github/workflows/visual-testing-on-push.yml
Adds missing github actions variable
Should fix the following:
- Related Issue #
- Closes #
=> Add missing github actions variable

dev-data/react-en.data.ts
update react team info
- Related Issue #764
- Closes #764 
=> 764-refactor: Update team description

src/widgets/hero/ui/hero.tsx
- Related Issue #940 
- Closes #940
=> 940-fix: Fix merch page image issue
